### ISSUE TITLE
Problem in compiling the program with SMASH 2.2.1

### ISSUE THREAD

**Issue by gabriele-inghirami** [doliinychenko/microcanonical_cooper_frye#3]
Hello

There is a problem in compiling the program with SMASH 2.2.1.
I attach the log file with the steps done and the error that I obtained.
[log.txt](https://github.com/doliinychenko/microcanonical_cooper_frye/files/8786265/log.txt)

The problem is likely related to some changes in the code by AxelKrypton in the last months regarding the detection of the machine endianness. I guess that the issue can be fixed with some minor adjustments.

Thank you very much for your kind attention and for the useful code. :)

**Comment by AxelKrypton** [comment]
From the log you attached, the
> `#error Endianness macro of the machine not defined.`

hints to the fact that no macro about endianness is defined, neither `LITTLE_ENDIAN_ARCHITECTURE` nor `BIG_ENDIAN_ARCHITECTURE`. I did not read further how SMASH is included and compiled, but in SMASH one of those macro is defined [in the top-level CMake file](https://github.com/smash-transport/smash/blob/843333d9a7ea0d11bfb7e0c006f3287b71fd0e64/CMakeLists.txt#L42-L60).

**Comment by doliinychenko** [comment]
Copypasted a piece of code from SMASH CMakeLists.txt that determines endianness. The master branch compiles and runs again. Please let me know if you still have any problems.

**Comment by gabriele-inghirami** [comment]
Yes, now it compiles, thank you!
